version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    container_name: yeoman-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  job:
    build:
      context: .
      target: job
    container_name: yeoman-job
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DB: postgres
      DB_HOST: db
      DB_TABLE: postgres
      DB_PORT: 5432
      SSL_MODE: disable
    ports:
      - 8090:8090
    depends_on:
      - db
    networks:
      - fullstack

  server:
    build:
      context: .
      target: server
    container_name: yeoman-server
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DB: postgres
      DB_HOST: db
      DB_TABLE: postgres
      DB_PORT: 5432
      SSL_MODE: disable
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge